export const reportBaseSelect = {
  id: true,
  reporterId: true,
  title: true,
  description: true,
  category: true,
  severity: true,
  status: true,
  isAnonymous: true,
  language: true,
  classificationScore: true,
  classificationLabel: true,
  suggestedCaseType: true,
  suggestedPriority: true,
  classificationConfirmed: true,
  location: true,
  gpsLat: true,
  gpsLng: true,
  ipAddress: true,
  ipHash: true,
  deviceFingerprint: true,
  detectedCountry: true,
  detectedRegion: true,
  detectedCity: true,
  locationMismatchWarning: true,
  locationMismatchConfirmed: true,
  contactEmail: true,
  riskScore: true,
  flaggedAsRepetitive: true,
  isDuplicate: true,
  trackingNumber: true,
  createdAt: true,
  updatedAt: true,
  resolvedAt: true,
  caseAssignment: {
    select: {
      id: true,
      caseType: true,
      status: true,
      notes: true,
      assignedTo: {
        select: {
          id: true,
          name: true,
          type: true,
        },
      },
      supportProviders: {
        select: {
          id: true,
          name: true,
          type: true,
        },
      },
    },
  },
} as const;
